version: '3.0'

expectations:
  population_size: 100000

actions:

  extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather

  km:
    run: r:latest analysis/km.R
      --df_input output/input.feather
      --dir_output output/km_estimates/
      --exposure sex
      --subgroups previous_covid_test
      --origin_date start_date
      --event_date death_date
      --censor_date dereg_date
      --min_count 6
      --max_fup 200
      --fill_times TRUE
      --plot FALSE
    needs: [extract]
    outputs:
      moderately_sensitive:
        feather: output/km_estimates/*.feather
        #png: output/km_estimates/*.png

