version: '3.0'

expectations:
  population_size: 100000

actions:

  extract:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/extract.arrow
    outputs:
      highly_sensitive:
        cohort: output/extract.arrow

  km:
    run: r:v2 analysis/km.R
      --df_input output/extract.arrow
      --dir_output output/km_estimates/
      --exposure sex
      --subgroups age_group
      --origin_date first_vax_date
      --event_date second_vax_date
      --censor_date censor_date
      --min_count 6
      --max_fup 365
      --concise TRUE
      --plot FALSE
    needs: [extract]
    outputs:
      highly_sensitive:
        feather: output/km_estimates/*.arrow
      moderately_sensitive:
        csv: output/km_estimates/*.csv
        #png: output/km_estimates/*.png


