version: '3.0'

expectations:
  population_size: 100000

actions:

  extract:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format feather
    outputs:
      highly_sensitive:
