version: '3.0'

expectations:
  population_size: 100000

actions:

  extract_fixed:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/extracts/extract.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract.arrow

  km:
    run: r:latest analysis/km.R
      --df_input output/input.feather
      --dir_output output/km_estimates/
      --exposure sex
      --subgroups age_group
      --origin_date first_vax_date
      --event_date second_vax_date
      --censor_date censor_date
      --min_count 6
      --max_fup 365
      --fill_times TRUE
      --plot FALSE
    needs: [extract]
    outputs:
      highly_sensitive:
        feather: output/km_estimates/*.feather
        #png: output/km_estimates/*.png

